name: .NET Build + Test + Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:PostBuildEvent=
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Publish 64bit
      run: dotnet publish --os win --arch x64 -c Release
