name: .NET Build + Test + Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:PostBuildEvent=
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Publish 64bit
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os win --arch x64 -c Release src/Randomizer.App/Randomizer.App.csproj
    - name: Publish 32bit
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os win --arch x86 -c Release src/Randomizer.App/Randomizer.App.csproj
    - name: Building the installer
      if: ${{ github.event_name != 'pull_request' }}
      working-directory: setup
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "randomizer.app.iss"
      shell: cmd
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: "setup/Output/*"
        name: files
